version: '3'
services:
  db:
    image: postgres:13.4
    container_name: postgres
    environment:
        POSTGRES_DB: kaggle
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    ports:
        - 5432:5432
    volumes:
        - ./db/data:/var/lib/postgresql/data
      
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=""
    container_name: jupyterlab
    depends_on: 
      - mlflow
      - db
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - ./projects:/home/projects
    
  mlflow:
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile
    command: mlflow server --backend-store-uri /home/mlruns --host 0.0.0.0 --port 5000
    container_name: mlflow
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./mlruns:/home/mlruns

  streamlit:
    build:
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    command: streamlit run struns/main.py
    container_name: streamlit
    depends_on: 
      - db
    ports:
      - "8501:8501"
    volumes:
      - "./struns:/usr/src/app/struns"

  pgadmin4:
    image: dpage/pgadmin4:5.0
    container_name: pgadmin4
    ports:
        - "8000:80"
        - "443:443"
    volumes:
        - ./pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - db
    restart: always